### ISSUE TITLE
WOOL Editor - Bug: Error saving .wool script ENOENT

### ISSUE THREAD

**Issue by hopdenakker** [woolplatform/wool#94] opened 2021-08-19 14:11 UTC
**Editor Version:**
v1.10.2

**Desktop or Web version:** 
Desktop

**Operating System (Desktop) or Browser (Web):**
macOS Big Sur 11.5.1

**Describe the Issue:**
When saving a WOOL script, the Editor says "Saved to /Users/.../project-name/en/start.wool". Then, when pressing OK an error message pops up saying "Error Saving Data to /Users/…/project-name/en/start.wool: Error: ENOENT: no such file or directory, open ‘/Users/…/project-name//Users/.../project-name/en/start.wool" (note that the directory is repeated here).

**Comment by borisvanschooten** [comment] 2021-09-02 07:01
Cannot reproduce this on my macos 10.15.6 now. My first guess is that the problem is caused by something in the "..." part of your directory. So I would like to know what's there.

**Comment by dennishofs** [comment] 2021-09-02 07:27
I can reproduce it on MacOS 11.2.3. I downloaded the zip file to my downloads folder and double-clicked it so I got folder `Wool-darwin-x64`. I'm running the editor from: `/Users/dennishofs/Downloads/Wool-darwin-x64/Wool.app`

I create new project `MyTest` inside my documents folder: `/Users/dennishofs/Documents/wool/MyTest`. The start file is created successfully here:
`/Users/dennishofs/Documents/wool/MyTest/en/start.wool`

In the editor I make some changes, then choose File > Save. It says "Saved to /Users/dennishofs/Documents/wool/MyTest/en/start.wool". I click OK and then it says "Error Saving Data to ..." My changes have not been saved.

By the way I think it's pretty hard to bypass the security measure in MacOS that prevents opening an uncertified download such as the WOOL Editor.

**Comment by borisvanschooten** [comment] 2021-09-03 15:05
Thanks for the feedback Dennis. I will try updating my mac to the latest MacOS version.

**Comment by borisvanschooten** [comment] 2021-09-09 07:06
I tried it with MacOS Big Surt 11.5.2, but I still cannot reproduce the problem. I re-downloaded version 1.10.2, created a project in /Users/bvanschooten/Documents/TestProject, tried saving start.wool.  No errors and the file is saved.  I am a bit stumped now. It would help if I knew what's in your javascript console.

What problem do you have with opening an uncertified download (this may be related).  What I do is select "Open" via the right click menu, then I get the warning about an uncertified download, with the option "Open".  Once I select Open I don't get the warning again.

**Comment by dennishofs** [comment] 2021-09-09 07:30
Here is a screenshot when I open the editor the first time:

![wool-not-verified](https://user-images.githubusercontent.com/11291522/132641704-02cb3fee-1768-4fd2-b156-46efbc339541.png)

So there's no Open button. I clicked the question mark and found that I need to open the System Preferences, Security & Privacy. Still there was nothing I could do there. I had to cancel the warning first. Then go back to the system preferences and only then I saw "Wool was blocked ..." with the button Open Anyway. I click that, another warning where I could click Open, and then the editor is opened.

**Comment by dennishofs** [comment] 2021-09-09 07:38
Nothing appears in the Javascript console when I try to save. Here is a screenshot of the error with the console opened. What you see in the console was there before I tried to save.

![wool-save-error](https://user-images.githubusercontent.com/11291522/132643250-8f222fd3-92b5-4cf4-9725-30f8323938a1.png)

**Comment by borisvanschooten** [comment] 2021-09-09 08:23
Thanks for the screenshot. I see there's something wrong with the reported path.  The root directory is repeated.  That helps some!  

About opening the editor for the first time: If I open via double click, I get the dialog that you posted here, with no Open option. However, if I open via "Open" on the right click menu, I do get the "Open" option.

**Comment by hopdenakker** [comment] 2021-09-09 08:42
Yes, the path is repeated in the error message - it's like it's trying to save to "DIR"+"FULL_PATH" instead of "DIR"+"FILENAME".

**Comment by borisvanschooten** [comment] 2021-09-09 11:42
Will be fixed on next release. This was not a mac-specific issue.  On creating a project, file path was initialised with absolute path rather than relative.   The bug manifests itself when you save the file right after creating the project, without first selecting it from the file tree.

**Closed** 2021-09-09 11:42 UTC
Labels: bug, editor
